# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
# https://docs.docker.com/engine/api/v1.41/#operation/ContainerList
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.20.0.2:3100/loki/api/v1/push

scrape_configs:
  - job_name: application_logs
    file_sd_configs:
      - files:
        - /vol/software/application/deployables/logs/*.log
    static_configs:
      - targets:
          - localhost
        labels:
          job: application_logs
          __path__: /vol/software/dcb_test/application/deployables/logs/*.log
